### ISSUE TITLE
Instance admin doesn't update, however from library it looks like it should update

### ISSUE THREAD

**Issue by atteroTheGreatest** [Syncano/syncano-python#11]
Here, I get an admin object and try to change its first name:
```
Out[59]: <InstanceAdmin: 2>

In [60]: ad.first_name
Out[60]: u'Robert'

In [61]: ad.first_name
Out[61]: u'Robert'

In [62]: ad.first_name = 'Roberto'

In [63]: ad.save()
Out[63]: <InstanceAdmin: 2>

In [64]: ad.first_name
Out[64]: u'Robert'

In [65]: ad.first_name = 'Roberto'

In [66]: ad.first_name
Out[66]: 'Roberto'

```

After save it returns to the original version which is a really weird behavior.

**Comment by dancio** [comment]
admin can be update but only the `role` field, we cloud raise error when field is read only or something but it leads to few more problems :P

**Comment by dancio** [comment]
@atteroTheGreatest warning for now will do the trick?

**Comment by atteroTheGreatest** [comment]
Yeah, warning would be good.
