### ISSUE TITLE
updating class doesn't reflect in dashboard...

### ISSUE THREAD

**Issue by sirvon** [Syncano/syncano-python#116]
I'm using this code to update/add fields to an exisiting class....

```python
import syncano                                                                                                                              
import time
from lib import settings
from syncano.models import Object
from syncano.models import Class
 
settings = settings.ConfigMixin()
 
connection = syncano.connect(api_key=settings.syncanoAccountKey)
CLASS_NAME = Class.please.get(instance_name='global', name='inappuserevents')
print(CLASS_NAME)
CLASS_NAME.schema.add = [{"name": "remoteid", "type": "string"}]
```

the dashboard isn't reflecting any changes...

what gives?

thx

**Comment by lifcio** [comment]
@sirvon Sorry for that, it's a bug in our docs, I already fixed that - thanks for noticing!

It should be:
```python
CLASS_NAME.schema.add({"name": "remoteid", "type": "string"})
CLASS_NAME.save()
```
`.add()` is a method call and should be passed the property you'd like to add to the schema. Or you can just use the .set() method to overwrite on top of current schema e.g.:
```python
CLASS_NAME.schema.set([{'type':'file', 'name':'aFile'},{'type':'string', 'name':'aString'}])
CLASS_NAME.save()
```
Running `.save()` might show some warnings, but the changes will be saved. Let us know if there's something else you're struggling with.

Also, feel free to join our [Gitter channel](https://gitter.im/Syncano/community), you will be able to get answer faster for any quick questions that might come to mind :)

**Comment by sirvon** [comment]
thanks for the pointer to gitter and the solution....
