### ISSUE TITLE
callbacks.py issue

### ISSUE THREAD

**Issue by EricSchles** [Syncano/syncano-python#15]
There is a python module called callbacks.  Could we consider changing the name so that there is no conflict in case someone already has the module installed?  

This is for the simple reason that someone may want to do the following:

import callbacks AND
from syncano import callbacks

**Comment by atteroTheGreatest** [comment]
@EricSchles thanks for info. Can you specify the version of the lib in issues? The import that you mentioned is in version 3. Version 4 is in branch release/4.0 :).
