### ISSUE TITLE
Syncano connect should provide better documentation

### ISSUE THREAD

**Issue by atteroTheGreatest** [Syncano/syncano-python#6]
In [10]: syncano.connect?
Type:        function
String form: <function connect at 0x7f64001d4140>
File:        /home/att/Projects/syncano-python/syncano/__init__.py
Definition:  syncano.connect(*args, **kwargs)
Docstring:   Connect to Syncano API.

It isn't very helpful - what can I provide here as args of kwargs?

**Comment by dancio** [comment]
documentation is planned in next release
