### ISSUE TITLE
Can't connect to default syncano API, because of certificate verification

### ISSUE THREAD

**Issue by atteroTheGreatest** [Syncano/syncano-python#7]
Retrieving anything from api fails badly with SSLError:

SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

It should be either treated as a warning or library user should have an easy way to configure library to ignore this issue. Reading a readme I don't know yet how to fix this.

**Comment by dancio** [comment]
In debug mode SSL verification is ignored.

``
$ export SYNCANO_LOGLEVEL=DEBUG
``

I'll add this to README

**Comment by atteroTheGreatest** [comment]
Cool :), I've found it myself, but info in README.md is a good idea.

**Comment by atteroTheGreatest** [comment]
Hm, I know that it's closed now, but how about passing `verify_ssl` explicitly in connect? Sometimes users don't need all the DEBUG mess on their screen, but still wants to use the api. I think that it would be very useful in codebox for example.

**Comment by dancio** [comment]
ok
